package classes;
// Generated 05/10/2018 12:32:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private Integer aluId;
     private String aluNome;
     private String aluCpf;
     private Date aluNascimento;
     private Set matriculas = new HashSet(0);

    public Aluno() {
    }

	
    public Aluno(String aluNome, String aluCpf, Date aluNascimento) {
        this.aluNome = aluNome;
        this.aluCpf = aluCpf;
        this.aluNascimento = aluNascimento;
    }
    public Aluno(String aluNome, String aluCpf, Date aluNascimento, Set matriculas) {
       this.aluNome = aluNome;
       this.aluCpf = aluCpf;
       this.aluNascimento = aluNascimento;
       this.matriculas = matriculas;
    }
   
    public Integer getAluId() {
        return this.aluId;
    }
    
    public void setAluId(Integer aluId) {
        this.aluId = aluId;
    }
    public String getAluNome() {
        return this.aluNome;
    }
    
    public void setAluNome(String aluNome) {
        this.aluNome = aluNome;
    }
    public String getAluCpf() {
        return this.aluCpf;
    }
    
    public void setAluCpf(String aluCpf) {
        this.aluCpf = aluCpf;
    }
    public Date getAluNascimento() {
        return this.aluNascimento;
    }
    
    public void setAluNascimento(Date aluNascimento) {
        this.aluNascimento = aluNascimento;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


