package classes;
// Generated 05/10/2018 12:32:58 by Hibernate Tools 4.3.1



/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Integer matId;
     private Aluno aluno;
     private Disciplina disciplina;
     private Professor professor;

    public Matricula() {
    }

    public Matricula(Aluno aluno, Disciplina disciplina, Professor professor) {
       this.aluno = aluno;
       this.disciplina = disciplina;
       this.professor = professor;
    }
   
    public Integer getMatId() {
        return this.matId;
    }
    
    public void setMatId(Integer matId) {
        this.matId = matId;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }




}


