package classes;
// Generated 05/10/2018 12:32:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer proId;
     private String proNome;
     private String proCpf;
     private Date proNascimento;
     private Set matriculas = new HashSet(0);
     private Set disciplinas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(String proNome, String proCpf, Date proNascimento) {
        this.proNome = proNome;
        this.proCpf = proCpf;
        this.proNascimento = proNascimento;
    }
    public Professor(String proNome, String proCpf, Date proNascimento, Set matriculas, Set disciplinas) {
       this.proNome = proNome;
       this.proCpf = proCpf;
       this.proNascimento = proNascimento;
       this.matriculas = matriculas;
       this.disciplinas = disciplinas;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProNome() {
        return this.proNome;
    }
    
    public void setProNome(String proNome) {
        this.proNome = proNome;
    }
    public String getProCpf() {
        return this.proCpf;
    }
    
    public void setProCpf(String proCpf) {
        this.proCpf = proCpf;
    }
    public Date getProNascimento() {
        return this.proNascimento;
    }
    
    public void setProNascimento(Date proNascimento) {
        this.proNascimento = proNascimento;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }




}


